### ISSUE TITLE
Add session data on create

### ISSUE THREAD

**Issue by ix-xerri** [dresende/node-sessions#5]
Just to confirm. Is there a way to add session data during the creation of the session or does it have to be created and then use the session.set() to add data?

From what I am seeing its using session.set() after the session is created.
Thanks

**Comment by dresende** [comment]
It's easy to do this. Let me just make some changes.

**Comment by dresende** [comment]
`session.create()` already allows an object to be passed to create the session. `Sessions.prototype.httpRequest` was the one that did not accept any parameter for that. Now you have an (optional) parameter:

``` js
function handleRequest(req, res, next) {
    sessions.httpRequest(req, res, { initial: data }, function (...) {
        ...
    });
}
```
