### ISSUE TITLE
Integrating with Express

### ISSUE THREAD

**Issue by ix-xerri** [dresende/node-sessions#6]
I am trying to use this repository and integrating it with express.js

Here is what I am trying to do.

The first thing I do on each request is try to load or create a new session as an express middle layer. This works fine

``` js
//Load/Initiate Session and save it to req.session so that it is available for the duration of the request
app.use(function(req, res, callback){
    sessionHandler.httpRequest(req, res, function (err, session) {
        if (err) {
            return callback(err);
        }

        req.session = session;

        return callback();
    });
});
```

The following part I am having trouble with (I have simplified the code to avoid confusion).

``` js
var myname = 'Albert';

req.session.set("name", myname, function(err){
    console.log(req.session.get());
});
```

The console log only prints the 'expires' object variable. 

It seems that the object in the store is being updated but the object req.session is not. Would you suggest a way how to do that. I think this is a general bug and not just because I am using this as an express middlelayer.

Let me know what you think.
Thanks

**Comment by dresende** [comment]
This is very strange..

**Comment by dresende** [comment]
I updated version on npm so you can use that if you prefer.

**Comment by ix-xerri** [comment]
I also added the following on line 255

``` js
for(var attr in key){
    data[attr] = key[attr];
}
```
